#!/bin/sh

# Writes to standard output valid HTML code that displays a table of photos.

echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
echo "<html>"
echo "<head>"
echo "      <title>Pictures</title>"
echo "</head>"
echo "<body>"
echo "      <h1>Pictures</h1>"

# No arguments provided
if [ $# -eq 0 ]
then
  clear
  echo "Please provide the correct number of arguments." >&2
  exit 1

# Arguments provided
elif [ $# -gt 0 ]
then
  if `echo $1 | grep -q "^[0-9]*$"` && [ $1 -gt 0 ]
  then
    count=0
    col=$1
    shift
    # loop through photos 
    for i in $@
    do
      # If the file exists
      if [ -f $i ]
      then 
        # check for jpg
        if file $i | grep -q JPEG;
        then
          if [ $count -eq 0 ]
          then
            echo "<tr>"
          fi 
          # table tag 
          if [ $count -lt $col ];
          then
            echo "<td><img src=\"$i\" height=100></td>"
            count=`expr $count + 1`
          else 
            echo "</tr>
            <tr>
            <td><img src=\"$i\" height=100></td>"
            count=1
          fi
        else 
          echo "Incorrect file type.">&2
        fi
      else 
        echo "File does not exist.">&2
      fi
    done 

    if [ $count -ne 0 ]
    then
     echo "</tr>"
    fi
  fi
fi

echo "</table>"
echo "</body>"
echo "</html>"

