#!/bin/sh

echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
echo "<html>"
echo "	<head>"
echo "		<title>Pictures</title>"
echo "	</head>"
echo "<body>"
echo "	<h1>Pictures</h1>"


# total num of arguments passed > 0
if [ $# -gt 0 ]
then
  if `echo $1 | grep -q "^[0-9]*$"` && [ $1 -gt 0 ]
  then 
  	# if there is a second argument
    if [ $# -gt 1 ]
    then
      num_columns=$1
      # if 3rd argumnet is a directory
      if [ -d $2 ]
      then 
      	# loop through years
        for year in $2/*
        do
          if [ -d $year ]
          then
            echo "<h2>`basename $year`</h2>"
            echo "<table>"
            count=0 

            # loop through months
            for month in $year/*
            do
              if [ -d $month ]
              then # loop through each pictures and check if is a jpg file
              	for picture in $month/*
              	do
                  if file $picture | grep -q JPEG;
                  then
              	    if [ $count -eq 0 ]
              	    then
              	      echo "<tr>"
              	    fi 
              	    # count < than columns, add td tag in that row
              	    if [ $count -lt $num_columns ]
              	    then
              	  	  echo "<td><img src=\"$picture\" height=100></td>"
                      count=`expr $count + 1`
                    else
                	  echo "</tr>"
                      echo "<tr>"
                      echo "<td><img src=\"$picture\" height=100></td>"
                	    count=1
         		        fi
                  else 
                      echo "$picture is not a JPEG file." >&2
                  fi
                done
              fi
            done
            if [ $count -ne 0 ]
    	      then
      		    echo "</tr>"
    		    fi
            echo "</table>"	
          fi
        done 
      fi
    else
      echo "Missing directory." >&2
    fi
  else
    echo "Invalid user input." >&2    
  fi
else 
  echo "No arguments were passed." >&2
fi
echo "</body>"
echo "</html>"
